### ISSUE TITLE
pause bug into jar archive under linux with v0.6?

### ISSUE THREAD

**Issue by tuxun** [olivierperez/SoulGame#1]
Hi, when I try to run the precompiled JAR archive, i got some errors:
```
user@machinename:~$ java -jar SoulGameImpl-0.6.jar 
Starting game...
Exception in thread "DefaultDispatcher-worker-1" javax.imageio.IIOException: Can't read input file!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
	at fr.o80.gamelib.drawing.Cursor.<init>(Cursor.kt:21)
	at fr.o80.soulgame.SoulCursorManager.<init>(SoulCursorManager.kt:10)
	at fr.o80.soulgame.SoulGame.createCursorManager(SoulGame.kt:18)
	at fr.o80.gamelib.loop.GameLoop.setup(GameLoop.kt:84)
	at fr.o80.gamelib.loop.GameLoop.access$setup(GameLoop.kt:20)
	at fr.o80.gamelib.loop.GameLoop$start$2.invokeSuspend(GameLoop.kt:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
Should i try to compile the code from scratch?
Thanks again for your time and your awesome game.
Giftsub

**Comment by tuxun** [comment]
long story short: that happens when we only grab the .jar, then try to launch it without having the others files

**Comment by tuxun** [comment]
```at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
	at fr.o80.gamelib.drawing.Cursor.<init>(Cursor.kt:21)```
means the jar failed to find the cursor texture, no test or logging is made here ;)

**Comment by olivierperez** [comment]
Hey, thanks for creating the 1st issue!

I was writing an answer but I see this comment
> then try to launch it without having the others files

So, to be sure, does it work when you grab all the folders next to the jar file? (fonts, levels and sprites)

BTW, the TODO here would be:
- [x] Add more logs about this kind of errors

**Comment by tuxun** [comment]
```
Microsoft Windows [version 10.0.19043.985]
(c) Microsoft Corporation. Tous droits réservés.

c:\Program Files (x86)\Arduino\java\bin>java.exe "c:\Users\Thierry\Downloads\SoulGame-0.7\SoulGameImpl-0.7.jar"
Erreur : impossible de trouver ou charger la classe principale c:\Users\Thierry\Downloads\SoulGame-0.7\SoulGameImpl-0.7.jar

c:\Program Files (x86)\Arduino\java\bin>java.exe -jar "c:\Users\Thierry\Downloads\SoulGame-0.7\SoulGameImpl-0.7.jar"
Starting game...
Exception in thread "DefaultDispatcher-worker-1" javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(ImageIO.java:1301)
        at fr.o80.gamelib.drawing.Cursor.<init>(Cursor.kt:21)
        at fr.o80.soulgame.SoulCursorManager.<init>(SoulCursorManager.kt:10)
        at fr.o80.soulgame.SoulGame.createCursorManager(SoulGame.kt:18)
        at fr.o80.gamelib.loop.GameLoop.setup(GameLoop.kt:84)
        at fr.o80.gamelib.loop.GameLoop.access$setup(GameLoop.kt:20)
        at fr.o80.gamelib.loop.GameLoop$start$2.invokeSuspend(GameLoop.kt:42)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

c:\Program Files (x86)\Arduino\java\bin>
```
i think the problem is that the game use Wrong base folder path, When i pathA/java -jar pathB/game.jar, it should look for the files in pathB instead of pathA (tested under dos, release 0.7)

**Comment by tuxun** [comment]
no problem in the right root folder 
```Microsoft Windows [version 10.0.19043.985]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\Thierry>cd Downloads/Downloads
Le chemin d’accès spécifié est introuvable.

C:\Users\Thierry>cd Downloads

C:\Users\Thierry\Downloads>cd FormatFactory2021_04_21

C:\Users\Thierry\Downloads>cd SoulGame-0.7

C:\Users\Thierry\Downloads\SoulGame-0.7>java
'java' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\Thierry\Downloads\SoulGame-0.7>java

C:\Users\Thierry\Downloads\SoulGame-0.7>"c:\Program Files (x86)\Arduino\java\bin\java.exe" -jar SoulGameImpl-0.7.jar
Starting game...
```

**Comment by olivierperez** [comment]
@tuxun I've added log information about the name of the resource when it is not found. I'll close this this issue, feel free to reopen it if it's not fully fixed.
